---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  # - ./bazarr/ks.yaml
  - ./jellyfin/ks.yaml
  - ./prowlarr/ks.yaml
  - ./radarr/ks.yaml
  # - ./readarr/ks.yaml
  - ./sabnzbd/ks.yaml
  # - ./shared/ks.yaml
  - ./sonarr/ks.yaml
