---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: minio
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: quay.io/minio/minio
              tag: RELEASE.2023-12-23T07-19-11Z-cpuv1
            env:
              TZ: America/Chicago
              MINIO_UPDATE: "off"
              MINIO_BROWSER_REDIRECT_URL: "https://minio.${SECRET_DOMAIN}/"
              MINIO_SERVER_URL: "https://s3.${SECRET_DOMAIN}/"
              # CONSOLE_MINIO_SERVER: "https://minio.${SECRET_DOMAIN}"
              # MINIO_DOMAIN: "https://s3.${SECRET_DOMAIN}"
              # MINIO_API_CORS_ALLOW_ORIGIN: "https://minio.${SECRET_DOMAIN},https://s3.${SECRET_DOMAIN}"
              MINIO_PROMETHEUS_URL: "http://kube-prometheus-stack-prometheus.observability.svc.cluster.local:9090"
              MINIO_PROMETHEUS_JOB_ID: minio
              # MINIO_IDENTITY_OPENID_CONFIG_URL: "https://auth.${SECRET_DOMAIN}/.well-known/openid-configuration"
              # MINIO_IDENTITY_OPENID_CLIENT_ID: minio
              # MINIO_IDENTITY_OPENID_CLIENT_SECRET: "${SECRET_MINIO_OAUTH_CLIENT_SECRET}"
              # MINIO_IDENTITY_OPENID_SCOPES: "openid,profile,email,groups"
              # MINIO_IDENTITY_OPENID_REDIRECT_URI: "https://minio.${SECRET_DOMAIN}/oauth_callback"
            envFrom:
              - secretRef:
                  name: minio-secret
            args:
              - server
              - /data
              - --console-address
              - ":9001"
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /minio/health/live
                    port: 9000
                  initialDelaySeconds: 30
                  periodSeconds: 30
                  timeoutSeconds: 10
                  failureThreshold: 6
              readiness: *probes
              startup:
                enabled: false
            securityContext:
              runAsUser: 568
              runAsGroup: 568
              fsGroup: 568
              fsGroupChangePolicy: OnRootMismatch
              supplementalGroups: [100]
    service:
      main:
        ports:
          http:
            port: 9001
          s3:
            port: 9000
    serviceMonitor:
      main:
        enabled: true
        endpoints:
          - port: s3
            scheme: http
            path: /minio/v2/metrics/cluster
            interval: 1m
            scrapeTimeout: 10s
    ingress:
      main:
        enabled: true
        className: internal
        hosts:
          - host: &consoleHost "minio.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
          - host: &s3Host "s3.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: s3
        tls:
          - hosts:
              - *consoleHost
              - *s3Host
    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: cardhu-minio-v2
        globalMounts:
          - path: /data
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: node-role.kubernetes.io/control-plane
                  operator: DoesNotExist
