---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-nas
spec:
  capacity:
    storage: 200Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-client
  mountOptions:
    - noatime
    - nolock
    - bg
    - soft
    - nfsvers=4.1
    - intr
    - tcp
    - timeo=50
    - retrans=5
    - actimeo=10
    - retry=5 0 0
  nfs:
    path: /volume1/minio
    server: "${NAS_IP}"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-nas
  namespace: minio
spec:
  storageClassName: nfs-client
  resources:
    requests:
      storage: 200Gi
  volumeMode: Filesystem
  volumeName: minio-nas
  accessModes:
    - ReadWriteMany
