---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cardhu-minio-v1
spec:
  capacity:
    storage: 200Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: cardhu-minio
  mountOptions:
    - noatime
    - nolock
    - bg
    - soft
    - nfsvers=4.1
    - intr
    - tcp
    - timeo=50
    - retrans=5
    - actimeo=10
    - retry=5 0 0
  nfs:
    server: 192.168.1.95
    path: /volume1/minio
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cardhu-minio-v1
spec:
  storageClassName: cardhu-minio
  resources:
    requests:
      storage: 200Gi
  volumeMode: Filesystem
  volumeName: minio-nas
  accessModes:
    - ReadWriteMany
