---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cardhu-minio-v1
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.1.95
  path: /volume1/minio
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.1
  - noatime
  - nolock
  - bg
  - soft
  - intr
  - tcp
  - timeo=50
  - retrans=5
  - actimeo=10
  - retry=5 0 0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cardhu-minio-v1
spec:
  storageClassName: cardhu-minio-v1
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
