---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cardhu-minio-sc-v1
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.1.95
  share: /volume1/minio
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.1
  - noatime
  - nolock
  - bg
  - soft
  - intr
  - tcp
  - timeo=50
  - retrans=5
  - actimeo=10
  - retry=5 0 0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: nfs.csi.k8s.io
  name: cardhu-minio-pv-v1
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: cardhu-minio-sc-v1
  mountOptions:
    - nfsvers=4.1
    - noatime
    - nolock
    - bg
    - soft
    - intr
    - tcp
    - timeo=50
    - retrans=5
    - actimeo=10
    - retry=5 0 0
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: "192.168.1.95/volume1/minio##"
    volumeAttributes:
      server: 192.168.1.95
      share: /volume1/minio
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cardhu-minio-pvc-v1
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  volumeName: cardhu-minio-pv-v1
  storageClassName: cardhu-minio-sc-v1
