ansible_become_pass: ENC[AES256_GCM,data:JvXzshEeFqFUBsBbUQ==,iv:Udxjy9i1tfyEjo6bErVBUxuPKTO+tjZkEd2pNd53j3w=,tag:hyuqx1c2HhY5r7JjJSD+vg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15kdjgz2v33vet626wnu8dlnhletdpeeqvgvh5t9rtwjn84jpvepszq6st3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGUERhc3ZUTXprMytjRjRw
            eGpaNUozOHB2K0pyc283NDMyVXNqbXYzTGcwCmMyWGdYYjh6WmQ3WFJZNC9Vck9Q
            TGVmWE5iN2NBUWZaa1ZhSE1sNnd6dUUKLS0tIHZNRHBUVXhyR0RiZmh4a29NOXZT
            S2xlVExYbnVuUEczV2N2dkY2T2VFa0EK+2UQgmhtV1j18kNt45XSDsqsl80NOge2
            dTgQa2rY2ZQAbG9iGMfDGVgL6jkhp+R8DPotgtSXvV4fDc7GOqxt4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-04T03:06:52Z"
    mac: ENC[AES256_GCM,data:dvo4NUzTNNyAloy4dBv0JnFkjeWUX5HH1mdGc8EldRxBOFWeBpQLxtWN35HLWArYWkY8wx0y9adiy4oaBnD7/Mp0E3g3Tz6qCRjf4zNulridqOeVX+PF0A+ARyffs9YgY2KLA3MC7VmGolMSWALQh4oxgn6RoWSVCXmhRw+86hw=,iv:70l3v6W4NxOb3owNeBjiB2Xx10JmlpMOaFT6YdK/aJ4=,tag:vqNK10aXoJIkFnG3XBIbYg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
