ansible_become_pass: ENC[AES256_GCM,data:G/qx6nD6OYRpDC7tsw==,iv:ixbgsSC11zJ1Q7cGyFexF7UnOJH9tZszQZ6fKOQKo1w=,tag:dRYNCxoiT2KiH292xRqEog==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15kdjgz2v33vet626wnu8dlnhletdpeeqvgvh5t9rtwjn84jpvepszq6st3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVRk1QVnd0QU51WnlqYkZ4
            VnVNMVpTa3hLZE9DTXFhREtrem41QUNqbURjCkNtOXh3alZXY0toSDBPdkI1RjFV
            RnZPLzB5REpRZmlZYmV6dUt3akhISkEKLS0tIEtlSS9hMGMyYlRLS3RjNHA0Mmcv
            L0M4YU1ZVlg5bVhsWkszcnNiUjJuTjQKGmtSF29eQANs7aWwHFZMXx1KK5n4SVJM
            Rb8lCwVH5+7RFAH4m56RQPpfYpao57rfsXX+J2cpD2m7kvzyNqC6iA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-04T04:37:41Z"
    mac: ENC[AES256_GCM,data:Jtyaz2Aj17uprlFB0+/198osLvM7yHMCSdyjsGn75FOK/frrb4Bg2JTL+s7z8Kr8vpmUFdxoUoXgTu8l9ILHgwFcbLblLDr1LtBAL5aS8gN1nWJkoT5ccTE0y6POKdVR6p3UWOLS4DlpiowNdw0AJEpSzSQjxzClo8XxAD3t2O4=,iv:1ZLEnWKqA7CXGo2+qBHLluLzAa4XbHazeEKepdY1qUg=,tag:f3P7FPgwDIHUMI2yyyV2RQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
