ansible_become_pass: ENC[AES256_GCM,data:GbPZtfkUSRbmhjEP5w==,iv:HUWB6BaE0lMdCgCEAxMoMz1gBZ3kRS06XZmeXUSw5Tc=,tag:pHg0+FlUvm+pm3iYz6HtRA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15kdjgz2v33vet626wnu8dlnhletdpeeqvgvh5t9rtwjn84jpvepszq6st3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiTHdickVYZGhmb3BKQnlZ
            UEwyVWNCZWtiR3czT3Bzcnl4Z04rZ21KUmhFCkxHS05nOUs0NVNJTmwrcFNVbVJQ
            WERpYnlxSlRkQ2JNWkcxRXBydjNXd00KLS0tIDF1VW5LNENvOXJXWXJOeU0rUWxH
            TEl6OGtaQ2tLTFNVdnh4R05La3NGZlUKoCfw4txUR0UgPZrvPKe+Da2Du+3XMnif
            uJ61ZkSWc1MnAjjs5uqOEFtdVc3H8JdqtL03dMjFVmaULNz6vhKg3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-04T04:37:42Z"
    mac: ENC[AES256_GCM,data:dkdEvbPmcfUfDkxK5ZxcsdyXdLmFXfygVsOKz80eSHjXWTAnbMNKyHi7/M014krHTJo6IPr2WrfrVzRKBkyJWOJHlVPnFnZwDPX5PepD0DSTVe6FDP/D1Zq7SIBVymhEf95zFR8FE9rqeh/1kuGxZhCv6n2FTS6O7jwv7WTBQY8=,iv:sktEVRCexgQ2oIyoLwumlD43/cMKRNKyyVr6DqE9kMw=,tag:dsM82VWUvAcc5AUxk7F6og==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
