ansible_become_pass: ENC[AES256_GCM,data:FUQyqNSurE6X24oJkw==,iv:WheNxcA7uMCtWUIs741qxZpntkoIPjIjf3/z9XIpcds=,tag:bPsnWiEyChnO4dK+GT0/Wg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15kdjgz2v33vet626wnu8dlnhletdpeeqvgvh5t9rtwjn84jpvepszq6st3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3RHY2VE5qeTFzZ3docWtV
            S1Z1RURaTnlxUmdEZ0twenVqYmI2SnZjcFFRCk5QdkJDeG9hVzIrTzF6OWVwNmlW
            TWxxck85Z0w1VzN0Z2FOYndzMERIcVEKLS0tIFozTFd5bzZJMVlVNGZpa2d2UTQ1
            akx3eVlOUjB4SzVvWndPdFRiQ1g1RDQKrkcBWIlgXnwvkQLqZBpBZNOBZQJEx01z
            qv1Qm6rinhUuS6pZ+bmIpUxus72j119LsfPmljvLbGZUmXnLYOYp0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-04T04:37:42Z"
    mac: ENC[AES256_GCM,data:N1YLbQCwGhUVNZ9ynhlyQk5NQhnhl85NyBkKWOxSCGWMfT4Uq63qY7MberFRBHfwmkVxgoi17qoQ826rR9fZiUTYb5G/RIpDs7ZJTGxEfTQGvYU1KUgK09oZn4h/hI/23wcb8H3DHaWmZ7as/7IbOzrHMCVLoAYo3WZxu6dpTjs=,iv:Ptqh50MQGtZeqKqIHiDBBNwboZlIIa0ASbYGNfQneL4=,tag:1QxmvEhhaEVD4h4Ou3fRCw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
