---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nzbget
  namespace: media
spec:
  interval: 6h
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 1h
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: ghcr.io/onedr0p/nzbget
      tag: 21.1@sha256:4735c87fbc75b781039c958292c485b31078fc886e682b641b86fc09e3621956
    env:
      TZ: "America/Chicago"
    service:
      main:
        ports:
          http:
            port: 6789
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        hosts:
          - host: &host "nzbget.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        type: pvc
        existingClaim: nzbget-config
      downloads:
        enabled: true
        type: pvc
        existingClaim: nzbget-downloads
        mountPath: /media/downloads
      media:
        enabled: true
        type: pvc
        existingClaim: nas-media
        mountPath: /media/cardhu-warehouse1
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      supplementalGroups:
        - 100
        - 1000
        - 1001
    resources:
      requests:
        cpu: 1
        memory: 2Gi
      limits:
        memory: 20Gi
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: node-role.kubernetes.io/control-plane
                  operator: NotIn
                  values:
                    - "true"
