apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:rjQiyzRAlvAPPAhzIns0SUhvXClq7IoJuv3p0c0Oi0ixvejK,iv:g9TxBFJkjaJ3LOOqIUoyB3Hl1fdwd505Mq3svi/bUUw=,tag:j9krS+xhmx+SMVz3oMni7w==,type:str]
    credentials.json: ENC[AES256_GCM,data:WHgKH4ViyRKLJCSCLBt7ZL+XHBciGzTNcL3KLTFCDTnF04ZuJpPHbpAeLPtxibM0kIrpVROiZSqFVPbM5RzlzBcxeha05htwiSK9CdI1z15zehsE0aLNQ/+7INeaEBCzXpSCjxiD7BzbSbj2Xwy3fc0kvqFVuzHOTNGGnPIm+2AtrTaorFsCSOg89wZHuOzDJm1fBYuA5hYqTHI0HXlzipx86EhE2qJF0y/oqmy44A==,iv:D/hXBbo1IWgPBM9HiTixtQlqto9Cb1DvZSmO6PMxNjk=,tag:WE51I3Pc6H0yDDEZPfLVBA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15kdjgz2v33vet626wnu8dlnhletdpeeqvgvh5t9rtwjn84jpvepszq6st3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4QlEyOU10VlE2OEZEblR6
            SG0xdVloSFNYVUpVM1A3bnJwUzZ5Q2VpeHpNCmV3VUxQRk5EUUpOeTVkdWx6SkdE
            RkpsWGFQaG1BdVo1TG0rL0JtSHU0TFUKLS0tIG5nWTZJbGQ2ZEJsOWsrcDJWZmVp
            V0d6TStiSG96Rk1UcHY5T2JEYTlsZE0KTjNSTiTdfkXAJ3TsG3AMF5VpKCxIWI0u
            1uCYfu3qhMhJ2bYxHar9Yk8zBfxm4uN/pcuVLbLvZHjcXuEGCtP8RQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-04T03:07:29Z"
    mac: ENC[AES256_GCM,data:gx41ADflolXdUhxSX1Fik1G2m/7Gd6xjMmofJB6VF16l9mx6j2II9rXDzOD2qVIOe1XPKOaJ/awh90KpNqQCxJLOUBgoPUb7Y78l7AzEjaqoqBDLr5/+QB4np48oGYrMMCZr/rDH5Q1+z4xvZFzyJlG7LTHSTBo07f7PjTqJa40=,iv:Wt7/42dnoQgtxS1b/dvDMKHSDkRAZpq1SAlSzqKBrwc=,tag:m94fKz2JN8fQ6OOCrhXddw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
