---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.longhorn.io
      chart: longhorn
      version: 1.6.0
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  values:
    persistence:
      defaultFsType: ext4
      defaultClassReplicaCount: 2
      reclaimPolicy: Retain
    defaultSettings:
      backupTarget: "nfs://192.168.1.95:/volume1/longhorn-system/backup"
      defaultLonghornStaticStorageClass: longhorn
      storageMinimalAvailablePercentage: 10
    ingress:
      enabled: true
      ingressClassName: internal
      host: "longhorn.${SECRET_DOMAIN}"
      tls: true
    longhornUI:
      replicas: 2
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoExecute"
    longhornManager:
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoExecute"
    longhornDriver:
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoExecute"
