---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: storage
spec:
  interval: 30m
  chart:
    spec:
      # renovate: registryUrl=https://charts.longhorn.io
      chart: longhorn
      version: 1.4.2
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  values:
    persistence:
      defaultFsType: ext4
      defaultClassReplicaCount: 2
      reclaimPolicy: Retain
    defaultSettings:
      backupTarget: "nfs://192.168.1.95:/volume1/longhorn-system/backup"
      defaultLonghornStaticStorageClass: longhorn
      storageMinimalAvailablePercentage: 10
    ingress:
      enabled: true
      ingressClassName: "nginx"
      host: "longhorn.${SECRET_DOMAIN}"
      path: /
      tls: true
    longhornManager:
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
    longhornDriver:
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
    longhornUI:
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
