---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/grafana.integreatly.org/grafanaserviceaccount_v1beta1.json
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaServiceAccount
metadata:
  name: grafana-mcp
spec:
  name: grafana-mcp
  instanceName: grafana
  role: Viewer # Needs "Editor" for `disableWrite: true` in HR
  isDisabled: false
  tokens:
    - name: grafana-mcp
      secretName: grafana-mcp-secret
