---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: grafana-mcp
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    # renovate: datasource=docker depName=ghcr.io/grafana-community/helm-charts/grafana-mcp
    tag: 0.23.1
    digest: sha256:cd78919b6ecd7b4f92fd8b1937a2c9d84aeec198ccea5f34f2ee2a80def37c12
  url: oci://ghcr.io/grafana-community/helm-charts/grafana-mcp
