---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: grafana-mcp
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    # renovate: datasource=docker depName=ghcr.io/grafana-community/helm-charts/grafana-mcp
    tag: 0.20.0
    digest: sha256:a381a72eeffd3a232281e765b1750e8dfd5a38330c9ca0728ce28d141665a3e8
  url: oci://ghcr.io/grafana-community/helm-charts/grafana-mcp
