---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: grafana-mcp
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    # renovate: datasource=docker depName=ghcr.io/grafana-community/helm-charts/grafana-mcp
    tag: 0.16.0
    digest: sha256:d0fe19e6baec9cb977ec3b11cff7e3fc2da79eb709f2e0b9fab0491dce0b82d0
  url: oci://ghcr.io/grafana-community/helm-charts/grafana-mcp
