apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:wG5sTyMTmtRcsZeuXvBRwIGjnDYQ9KyN,iv:hNEGWNiNkPnzdP2E+YFGNv7f5qU27FIZlUfcdPDq4Ug=,tag:u0LNtntBa52HUH8WYfAhRg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15kdjgz2v33vet626wnu8dlnhletdpeeqvgvh5t9rtwjn84jpvepszq6st3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDbFJnTCtBS0ZIdnorRzlP
            K210U0Y4MGpKNFZBV0IxT0tOU0NwdUNGbUE4Cmx0YzFhYWlKMTFtd1FFUFVaL2RZ
            VnJHS0RIaGZ0MGxkSHdTYy9IQUJXNEkKLS0tIEJjZXdYNzZySkt0UUdBTkVGMVc1
            OHM5dDVtbVp6eWhIdXBTVVJmYkIvZ0UKXZ9w+iZrMIYQtufYjtqKG6dV+RscGOmy
            ITQdNNbW31cFcGqTbtiNRDf/ZVcBgCvvzB51bPAPg3RQ+YHVZ4W9/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-04T04:38:14Z"
    mac: ENC[AES256_GCM,data:4Fw3RhRwOxxJRFIstxzkJhkJmkwslpO5CTjX6AcOqD0s0e71jFqXZBFtTOjNpJhFGCZ3gCLO3S7nrQwh2LlH+HYcJth9lgwckqwyAAxvwUHVsNunqBPcGBoSOeqJoOwD+K8xlSSrXqz4n4ulAscWHpoTdj+zu7EhBR4Glo4aIRQ=,iv:CkGLZAbD/c93Oo+va+S7xTxvv2uDeWkE7/UXltnlk0Q=,tag:lt5xjpnGJ3q+ANgO6PYLOw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
