---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: audiobookshelf
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 5.0.1
    digest: sha256:e99ebe581c41a38e1fa282bf53d4306b5cba01a27f89543583dc0817b8fa6558
  url: oci://ghcr.io/bjw-s-labs/helm/app-template
