---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ./helmrelease.yaml
  - ./ocirepository.yaml
  - ./storageclass.yaml
  - ./o11y
configMapGenerator:
  - name: ollama-exporter-configmap
    files:
      - ollama-exporter.yml=./resources/exporter-config.yaml
generatorOptions:
  disableNameSuffixHash: true
