---
apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: "daily-backup"
  namespace: longhorn-system
spec:
  cron: "0 4 * * ?"
  task: "backup"
  groups:
    - default
  retain: 2
  concurrency: 2
  labels:
    interval: daily
