---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: toolhive-operator
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.51.2
    digest: sha256:273b4bf2ce42ac1bfe0e5bc7507b3be0674a685997b0488ed8adf79f620a72c8
  url: oci://ghcr.io/stacklok/toolhive/toolhive-operator
