---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grimmory
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: grimmory-secret
    template:
      engineVersion: v2
      data:
        MARIADB_USER: "{{ .GRIMMORY_MARIADB_USER }}"
        MARIADB_PASSWORD: "{{ .GRIMMORY_MARIADB_PASSWORD }}"
        MARIADB_ROOT_PASSWORD: "{{ .GRIMMORY_MARIADB_ROOT_PASSWORD }}"
        DATABASE_USERNAME: "{{ .GRIMMORY_MARIADB_USER }}"
        DATABASE_PASSWORD: "{{ .GRIMMORY_MARIADB_PASSWORD }}"
  dataFrom:
    - extract:
        key: grimmory
