---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/refs/tags/app-template-5.1.0/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: recyclarr
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: recyclarr
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        type: cronjob
        cronjob:
          schedule: "0 4 * * *"  # daily at 04:00
          timeZone: "${TIMEZONE}"
          concurrencyPolicy: Forbid
          successfulJobsHistory: 1
          failedJobsHistory: 1
          backoffLimit: 0
          ttlSecondsAfterFinished: 86400
        pod:
          restartPolicy: Never
        containers:
          main:
            # renovate: datasource=docker depName=ghcr.io/recyclarr/recyclarr
            image:
              repository: ghcr.io/recyclarr/recyclarr
              tag: 8.7.2@sha256:6e69e009e1cd7493ff6093e8e187b5d3788c75b4a2c0c5127b6a1beda1c19728
            args:
              - sync
            env:
              RECYCLARR_DATA_DIR: /tmp
            envFrom:
              - secretRef:
                  name: recyclarr-secret
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 512Mi
    persistence:
      config:
        type: emptyDir
        globalMounts:
          - path: /config
      config-file:
        type: configMap
        name: recyclarr-configmap
        globalMounts:
          - path: /config/recyclarr.yml
            subPath: recyclarr.yml
            readOnly: true
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
    defaultPodOptions:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: DoesNotExist
