---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/grafana.integreatly.org/grafana_v1beta1.json
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
spec:
  external:
    url: http://grafana.observability.svc.cluster.local
    adminUser:
      name: grafana-admin-secret
      key: admin-user
    adminPassword:
      name: grafana-admin-secret
      key: admin-password
    tenantNamespace: default
