apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
stringData:
    admin-password: ENC[AES256_GCM,data:LUMZYDH8H56wKC1NFhO3Xu3U0w5nOA==,iv:cmo03/P0RJ7F9QA3nQncWaSBFed5vywNui/DLMf0SlU=,tag:YkCVewtRNEpwaEowpaCNJw==,type:str]
    admin-user: ENC[AES256_GCM,data:qOpO+gA=,iv:jAFdywsVLURssIVRheICMMyxArKMuCh005LCV5JFz0w=,tag:MiEzzaITbPmP17Mv6RSldA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15kdjgz2v33vet626wnu8dlnhletdpeeqvgvh5t9rtwjn84jpvepszq6st3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrQWFjUzZrZFN4eWhqZUp4
            anRqY0lJdElhdW5rc0lqRGF3dnhjZGZ6NXlzCmJDQWdGRysyOHB2dXplMFNaUXJy
            SXZhT2VZZk83NWVXeTJCbG9WOXVWbm8KLS0tIFpmZVFNK0c3WUtEL0J1MzRUMG9X
            WXBlZGRlMURWKzRZR0VmV3U4VG9NNUUKUL9MOBE0JsdWfL6cVIHf/nZrPB28D684
            ErPygWiSZAuvThD0IFYF6VWh4n/FXFg34DNM/1BfYaeVRuZqPTDphg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-04T03:07:30Z"
    mac: ENC[AES256_GCM,data:n0ZP49arBbCARbbTqcQuoiURbJnTm6NHOjmL6y1U6hht5LOpVddRUHMvZhMQBnJbqMSWyZnRZ/a4uw1yGpUVkHyOaposT6Pr3YR6PRbTQuvNl2GlAgOfRtikIfvoZSN9e240uorzGOBhJnDeOUAPDkRDWYUKm30q77Tzpl8DbDM=,iv:Ek5Ez1PibtpVBLEwY6QZGF+0Gr599fB8Ictx8SDKiLk=,tag:/mEr3lVaQu//qkQkhZrKVw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
