apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
stringData:
    admin-password: ENC[AES256_GCM,data:Z3MIfi+TGRTee1i9bIJcPy7HQNL6Yg==,iv:RixAOdrczzMepUrHO0oj3542jm0IgDEAzjAqfF9rWc0=,tag:sOahhbK8mU+EJ1GlIntOjA==,type:str]
    admin-user: ENC[AES256_GCM,data:zWjOpJk=,iv:yG8oG5WHOSf/RrCKzn6u3kDgGidGOURcmIWjpyu3IcI=,tag:WAWBlGvc0LibE7RR6Yqm7Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15kdjgz2v33vet626wnu8dlnhletdpeeqvgvh5t9rtwjn84jpvepszq6st3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnajJPRkVTM1hoVEplLzZt
            UFVJMlBHbGJ0aGo5ZlJIbTM5TjV3U3FpQlVRCmszRGVSdkRGVlZQdTNxZlphaEt1
            aERZNTFWSHdLMjM3cFpVcldVR1lyZVUKLS0tIGpyRS9TZzFDbStjTlpnRzUrOEtT
            UEJIbUcxUFV2TGE3MVlNQkRZTDArYlEKOeSSnTrwGfaC09T1p2pXWmUHNn+ox96I
            k+1onmzSGGBiaDXlyEUwVmj/wWLMaukOabL7FOUfhDq3YzN4bWtZ+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-04T04:12:59Z"
    mac: ENC[AES256_GCM,data:zBL49e2DRjrG05fPL2YzcnNle9CeF6W6AxVvG8hilMqXX6Y9Ig8tahZoi/asH9DHx5207wwdIvE3lYH8nPv+O+BAZPeUG+Qmacx7XGvcwIYuTAvjqwA1W4YdU2Z9RmBNAF7YZhwtpl4cKN+owBE7u0oJm15yfAjoivwPq/AyeE8=,iv:Th87qUWS9uy9eJkAInUY7M5wQYsxewBBHiRr0i3NC2s=,tag:kJMMRZuH1Wc4zT3VR3W6qw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
