---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/toolhive.stacklok.dev/mcpserver_v1beta1.json
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: mcp-time
  namespace: mcp-platform
spec:
  # renovate: datasource=docker depName=docker.io/theo01/mcp-time
  image: "docker.io/theo01/mcp-time@sha256:68f2a2d78dc66efa84f30b7a5209c90da64bf936de923c20861122062ef8ff0f"
  args:
    - "--log-file"
    - "/dev/stderr"
  transport: stdio
  proxyMode: streamable-http
  proxyPort: 8080
  permissionProfile:
    type: builtin
    name: none
  telemetryConfigRef:
    name: mcp-time-telemetry
  audit:
    enabled: true
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  podTemplateSpec:
    spec:
      volumes:
        - name: tmp
          emptyDir: {}
      containers:
        - name: mcp
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: DoesNotExist
