---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/refs/tags/app-template-5.0.1/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: listenarr
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: listenarr
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/listenarrs/listenarr
              tag: canary-1.0.3@sha256:d14206d72c0d66b3398d002788d5e1ccdd99961de97430107d682ac8c39f8e6a
            env:
              TZ: "America/Chicago"
              COMPlus_EnableDiagnostics: "0"
              LISTENARR_PUBLIC_URL: "https://listenarr.int.${SECRET_DOMAIN}"
              LISTENARR_LOG_LEVEL: Information
            envFrom:
              - secretRef:
                  name: listenarr-secret
            probes:
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &port 4545
                  initialDelaySeconds: 10
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 30
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: *port
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 1Gi
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            runAsNonRoot: true
            fsGroupChangePolicy: OnRootMismatch
            supplementalGroups:
              - 100
              - 1000
              - 1001
    service:
      main:
        controller: main
        ports:
          http:
            port: *port
    ingress:
      main:
        enabled: true
        className: internal
        hosts:
          - host: &host "listenarr.int.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 10Gi
        storageClass: longhorn
        globalMounts:
          - path: /app/config
      tmp:
        type: emptyDir
      media:
        existingClaim: nas-media
        globalMounts:
          - path: /media/cardhu-warehouse1
            readOnly: true
          - path: /media/cardhu-warehouse1/audiobooks
            subPath: audiobooks
          - path: /media/cardhu-warehouse1/downloads/complete/audiobooks
            subPath: downloads/complete/audiobooks
    defaultPodOptions:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: DoesNotExist
