apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:YR/6UkDdNJqmNCh2O4OESMW9Nd7YfdBdYnaizjhxa5fKC0xPTQqaUQ==,iv:AbgPIpxAxqOKpU2jsVuz5dXXFX+IXuAefRWpsk2G6wk=,tag:+/Hy5QCMwfiLB0XXLL+oCA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15kdjgz2v33vet626wnu8dlnhletdpeeqvgvh5t9rtwjn84jpvepszq6st3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTWmEzcjM5N1B3S0VibHQ0
            RzJNUlhDUktDL2tZb3dtUVdZUzFGU0Y1MG1FCjUzMmFlZThjUE5TM0MrL2V1QTlj
            WGFIdkRndE9KQndvR3o4TDlUaHdvbmcKLS0tIElkbEE4U255cmMrWkQyZk0rYlJy
            ZWQrc09mQ0dqS2s3NURJbVk2QVZ6TmMKKPcF72J9gpFK6E1aZ1w7FspaTkxlFNWq
            IC82lPymRcfPhfv72Cgqzxn6eMtxFtHefOaZyhaahmYAH387R03BlA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-04T04:38:15Z"
    mac: ENC[AES256_GCM,data:c+4z+sPSokCwO6QHgnyI8V0GtMWTCRPEUs7wT0dHpKJ9/oA31+c4j11s8WpssdL+6TgSe8ue4/wUStbKluTfGepeZE1xxe0NCZ7mAcZCHVeyxIPCqIP1TA3TPjDCbo+uROw2ciKD+NqNH1MD1/gNzcl8NInEqzwxdYV4rFAwxIM=,iv:ghUCRGvjNQAE3RkNimxgxj3T/1v3vg0/8TQGPx7jf04=,tag:mZz4f1ngN3MTRHa9ef/0ug==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
