apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:a1DPOKox8XI62WW6ET5FgIVj6BD2A/KFdHnAeUykGqv1C9qKOQ==,iv:52NAPOQ4ROUjjgzs6tdt0Cw0zJySb+CI1wIz3RRrFZ8=,tag:Lqsy/l3BUdduXPU9ptfb9g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cg76rnnuuqr3ykr9hsdws3sd2frr40za7g5fje25ctwl7nh2k3lqw6rtef
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBRVFGRW5ZREdacitGaTZk
            LzdKZnpnbk43ZHdWYnU1alNIZ0ZtTFNMMlZ3CmlKUHNjZzZMbHd3SGhHcUpjVVhn
            VE95T0M1U2JaV08zZ1pJYkhzV3JlNjQKLS0tIE55a0Ztd2l2cDFpTU00QlY3MDky
            WFRKdDh3N2hsRXBPZ3E4d0gveGxMMTQKbAWOpzargqNnCc/DOf/dO4YyOr6iNQuh
            LpYUYiOf//jWLl56PT0U1jVUtCNNNlRItKxInPDON0fQmub/j3qlOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-28T03:01:15Z"
    mac: ENC[AES256_GCM,data:tKVE4VpGYNoRd+JWN90F0WOAM7EoTkez76+0mz8UI5WWNeD2URuHW30KIr5kte3Dmj0C+BHAotNQCoIVHhpQt3E8bnuK1eBD+fPaZegSLJ+EQXCx48KXeFW7YStzEEGgjOqXuDPjArhR17r5fqXWCgHFl6E13rhlPlmMDhT45e4=,iv:E1imXRGzT83pggSIRkOBAFuBR8DZeXqzuGe/HDeZny4=,tag:OfTbEIcQy2n0RzKIFGxm7w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
