apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:rDdt5hD8j1jjhIh514ApKmIzqA3LNxboH0zCwceLZ1whzhjfx4ndCw==,iv:jiI7kF+hPxfLd8Ac0DDXaYS1bp+P4pE6SckXfzCOPfE=,tag:PV608iaBrtAlnT6GEXkeig==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cg76rnnuuqr3ykr9hsdws3sd2frr40za7g5fje25ctwl7nh2k3lqw6rtef
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzd21JdFVHekl2YTcwaFll
            TnI5aHlCUXVKeG9HaTY3R3BRcytBY3JzeVE4CjJYMjFTRzhLZEdKVk12d0ZLZnRZ
            WVJSZzhSdkxpN0lzZGpLeEN1bjNCYm8KLS0tIHpFd1hVMGpmdWZUMnE2RDQwVEJu
            VlBHa0UvRHlIS3pZb1p0R3dnK0dXc2sKNYgk4oWfPMsxzKep8wGTa8R3pZ4sjWX7
            Vd+E3vE/g3rNHROU+r9ZxEtuY/6ZH8urKB65SDuhc9ex/Zro+dYDMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-15T23:55:10Z"
    mac: ENC[AES256_GCM,data:/YOIVe5A9bIgC0cpurde+4cGk8lUzdIPaSEskAnoTXiLWp4IKRlvH8yhM/gD6zjaNzyHMhmIcWjrC2LdtgJ81gh0/XxGcOmGxSBaYFpyyRPWHEPMTaPNI8YUp2SAsFTIZ6iy0ob9nkVqoxSdBGI0W6GLdW2jx3QxDFjj7ygOoeQ=,iv:u8JphOWAobhdUyWdgOmesYqU0UIzJbkWAgIiW2M4fZs=,tag:5scXoyngjQs4s5EGN9+14A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
