---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: coder
  namespace: dev
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: coder-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        CODER__POSTGRES_HOST: &dbHost postgres-v15-rw.database.svc.cluster.local
        CODER__POSTGRES_PORT: "5432"
        CODER__POSTGRES_USER: &dbUser "{{ .CODER_POSTGRES_USER }}"
        CODER__POSTGRES_PASSWORD: &dbPass "{{ .CODER_POSTGRES_PASS }}"
        CODER__POSTGRES_MAIN_DB: &dbName coder
        CODER_PG_CONNECTION_URL: "postgres://{{ .CODER_POSTGRES_USER }}:{{ .CODER_POSTGRES_PASS }}@postgres-v15-rw.database.svc.cluster.local/coder"
        # Github
        CODER_GITAUTH_0_ID: "{{ .CODER_GITAUTH_0_ID }}"
        CODER_GITAUTH_0_TYPE: "{{ .CODER_GITAUTH_0_TYPE}}"
        CODER_GITAUTH_0_CLIENT_ID: "{{ .CODER_GITAUTH_0_CLIENT_ID }}"
        CODER_GITAUTH_0_CLIENT_SECRET: "{{ .CODER_GITAUTH_0_CLIENT_SECRET }}"
        # GitHub OAuth
        CODER_OAUTH2_GITHUB_ALLOW_SIGNUPS: "{{ .CODER_OAUTH2_GITHUB_ALLOW_SIGNUPS }}"
        CODER_OAUTH2_GITHUB_ALLOWED_ORGS: "{{ .CODER_OAUTH2_GITHUB_ALLOWED_ORGS }}"
        CODER_OAUTH2_GITHUB_CLIENT_ID: "{{ .CODER_OAUTH2_GITHUB_CLIENT_ID }}"
        CODER_OAUTH2_GITHUB_CLIENT_SECRET: "{{ .CODER_OAUTH2_GITHUB_CLIENT_SECRET }}"
        # OIDC
        # CODER_OIDC_ISSUER_URL: "{{ .CODER_OIDC_ISSUER_URL }}"
        # CODER_OIDC_EMAIL_DOMAIN: "{{ .CODER_OIDC_EMAIL_DOMAIN }}"
        # CODER_OIDC_CLIENT_ID: "{{ .CODER_OIDC_CLIENT_ID }}"
        # CODER_OIDC_CLIENT_SECRET: "{{ .CODER_OIDC_CLIENT_SECRET }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: coder
    - extract:
        key: cloudnative-pg
