---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: coder
  namespace: dev
spec:
  interval: 30m
  chart:
    spec:
      chart: coder
      version: 2.17.2
      sourceRef:
        kind: HelmRepository
        name: coder
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    coder:
      initContainers:
        - name: 01-init-db
          image: ghcr.io/onedr0p/postgres-init:16.3
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: coder-secret
      serviceAccount:
        enableDeployments: true
        workspacePerms: true
        name: coder
        annotations: {}
      env:
        # DB
        - name: CODER_PG_CONNECTION_URL
          valueFrom:
            secretKeyRef:
              name: coder-secret
              key: CODER_PG_CONNECTION_URL
        # App
        - name: CODER_ACCESS_URL
          value: "https://coder.${SECRET_DOMAIN}"
        - name: CODER_WILDCARD_ACCESS_URL
          value: "*.coder.${SECRET_DOMAIN}"
          # value: "*-ws-coder.${SECRET_DOMAIN}"
        - name: CODER_TELEMETRY
          value: "false"
        - name: CODER_PROMETHEUS_ENABLE
          value: "true"
        #- name: CODER_DISABLE_PATH_APPS
        #  value: "true"
        # GitHub
        - name: CODER_GITAUTH_0_ID
          valueFrom:
            secretKeyRef:
              name: coder-secret
              key: CODER_GITAUTH_0_ID
        - name: CODER_GITAUTH_0_TYPE
          valueFrom:
            secretKeyRef:
              name: coder-secret
              key: CODER_GITAUTH_0_TYPE
        - name: CODER_GITAUTH_0_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: coder-secret
              key: CODER_GITAUTH_0_CLIENT_ID
        - name: CODER_GITAUTH_0_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: coder-secret
              key: CODER_GITAUTH_0_CLIENT_SECRET
        # GitHub OAuth
        - name: CODER_OAUTH2_GITHUB_ALLOW_SIGNUPS
          valueFrom:
            secretKeyRef:
              name: coder-secret
              key: CODER_OAUTH2_GITHUB_ALLOW_SIGNUPS
        - name: CODER_OAUTH2_GITHUB_ALLOWED_ORGS
          valueFrom:
            secretKeyRef:
              name: coder-secret
              key: CODER_OAUTH2_GITHUB_ALLOWED_ORGS
        - name: CODER_OAUTH2_GITHUB_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: coder-secret
              key: CODER_OAUTH2_GITHUB_CLIENT_ID
        - name: CODER_OAUTH2_GITHUB_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: coder-secret
              key: CODER_OAUTH2_GITHUB_CLIENT_SECRET
        # # OIDC
        # - name: CODER_OIDC_ISSUER_URL
        #   valueFrom:
        #     secretKeyRef:
        #       name: coder-secret
        #       key: CODER_OIDC_ISSUER_URL
        # - name: CODER_OIDC_EMAIL_DOMAIN
        #   valueFrom:
        #     secretKeyRef:
        #       name: coder-secret
        #       key: CODER_OIDC_EMAIL_DOMAIN
        # - name: CODER_OIDC_CLIENT_ID
        #   valueFrom:
        #     secretKeyRef:
        #       name: coder-secret
        #       key: CODER_OIDC_CLIENT_ID
        # - name: CODER_OIDC_CLIENT_SECRET
        #   valueFrom:
        #     secretKeyRef:
        #       name: coder-secret
        #       key: CODER_OIDC_CLIENT_SECRET
      ingress:
        enable: true
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        host: "coder.${SECRET_DOMAIN}"
        wildcardHost: "*.coder.${SECRET_DOMAIN}"
        # wildcardHost: "*-ws-coder.${SECRET_DOMAIN}"
      nodeSelector:
        node-role.kubernetes.io/worker: "true"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: In
                values:
                - "true"
