---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./namespace.yaml
  # - ./rbac.yaml
  - ./storageclass.yaml
