---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: coder
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 2.38.0
    digest: sha256:e2af4bde012d4bb282bde05fdf5d3da2643274d3f9ab98388658ff63ad613a38
  url: oci://ghcr.io/coder/chart/coder
