---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: coder
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 2.37.2
    digest: sha256:f8e2a5081151e2122c65c7d49d74dbd4d98510510e35de35d41f1a456dfcafef
  url: oci://ghcr.io/coder/chart/coder
