---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: coder
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 2.37.0
    digest: sha256:fffffd8450548dba728bbdd5b94df3a1ee26ff93493a8bc06612ada58f43fd0d
  url: oci://ghcr.io/coder/chart/coder
