---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: coder
  namespace: dev
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: kubernetes-dashboard
    meta.helm.sh/release-namespace: dev
subjects:
  - kind: ServiceAccount
    name: coder
roleRef:
  kind: Role
  name: coder-workspace-perms
  apiGroup: rbac.authorization.k8s.io
