---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: grafana-operator
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    # renovate: datasource=docker depName=ghcr.io/grafana/helm-charts/grafana-operator
    tag: 5.23.0
    digest: sha256:71039650b1a19ba1d9a2732cc30b35dadfaa6f06ae4224a9dcce640eb66fe1db
  url: oci://ghcr.io/grafana/helm-charts/grafana-operator
