---
apiVersion: v1
kind: ConfigMap
metadata:
  name: radarr-gatus-ep
  namespace: media
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: radarr
        group: guarded
        url: 1.1.1.1
        interval: 1m
        ui:
          hide-hostname: false
          hide-url: false
        dns:
          query-name: "radarr.${SECRET_DOMAIN}"
          query-type: A
        conditions:
          - "[STATUS] == 200"
#        alerts:
#          - type: pushover
