---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bazarr
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    initContainers:
      01-init-db:
        image: ghcr.io/onedr0p/postgres-init:14.9
        imagePullPolicy: IfNotPresent
        envFrom:
          - secretRef:
              name: bazarr-secret
    controller:
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: ghcr.io/onedr0p/bazarr
      tag: 1.3.0@sha256:afc68d92cc6fa5c8d5f578dc45304cf7785a583fe82590ed3efdaee224320d6c
    env:
      TZ: "America/Chicago"
    envFrom:
      - secretRef:
          name: bazarr-secret
    service:
      main:
        ports:
          http:
            port: 6767
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        hosts:
          - host: &host "bazarr.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 100
        - 1000
        - 1001
    persistence:
      config:
        enabled: true
        existingClaim: bazarr-config-v1
      add-ons:
        enabled: true
        type: emptyDir
        mountPath: /add-ons
      media:
        enabled: true
        type: pvc
        existingClaim: nas-media
        mountPath: /media/cardhu-warehouse1
      scripts:
        enabled: true
        type: configMap
        name: bazarr-scripts # overriden by kustomizeconfig
        defaultMode: 0775
        readOnly: true
    resources:
      requests:
        cpu: 10m
        memory: 250Mi
      limits:
        memory: 2Gi
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: node-role.kubernetes.io/control-plane
                  operator: NotIn
                  values:
                    - "true"
    sidecars:
      subcleaner:
        image: registry.k8s.io/git-sync/git-sync:v4.0.0
        imagePullPolicy: IfNotPresent
        args:
          - --repo=https://github.com/KBlixt/subcleaner
          - --branch=master
          - --wait=86400 # 1 day, in seconds
          - --root=/add-ons
        volumeMounts:
          - name: add-ons
            mountPath: /add-ons
