apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
stringData:
    password: ENC[AES256_GCM,data:uSPoFbxpBhoLkyzlP3Uxcc0/Zd0BB9bFrE0vWfigeG6FjaW2Lx0t1BL0MAnd//s1lUIol4Q92j3jvo/o,iv:Q0Y3Drou7OBCyMlw1yfx9iJqWV2o/zmxpocb8WXP86g=,tag:wdszg1+xqzkXdWujBTz3AQ==,type:str]
    username: ENC[AES256_GCM,data:7YO+PKU=,iv:6JtZZ2lX6jhORNCqDiWo77I323Y6nxRHf64QXX070X8=,tag:pQ8FNrx/pFdh3H06wueA+w==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15kdjgz2v33vet626wnu8dlnhletdpeeqvgvh5t9rtwjn84jpvepszq6st3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvMUZiTHBLd0RNRVB4WXRn
            OWZuam96ekNOdUhjSzRQUk9LbkJnNm5udFN3CnV6NGttSGx2VjVOL2JFYnpUWVFl
            RUZGbTAzaWtrL0orRXVDeXczdlNHWGsKLS0tIFRVVXRJQXNnNGVLNitnMDJYaFdW
            Qm8vdTFxWVJ0UnFtdE9BbDdld3hUdDAKzXcGi7I9PPveyoyzkKpUFkLOC9ygAqgz
            srC/1O32TNMIgVuNpW+D+SujWe0TTBi3okv1rkdeD8J1vy0mrPs/8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-04T04:38:21Z"
    mac: ENC[AES256_GCM,data:H6hakm6j5PD9bSpmmwxz+Vsq+hyabrAwP+kDfL6Y7DEFQ/wpJpJNEFNUl303HSqnnGf5CS1LcMPfvHJ8CCaZZFJZRAAKmRmyrwh9Nh5SS2346Xbb4ZecYliuPIhPfEgHQGlPvPQQh+HnF7nXYu3ejTK/GLvgJkY/n5G+z30wJAc=,iv:64oD+NZLVdzBiZomNk/XMzDTMJDPP0al5rU3qhG4N7g=,tag:KvIyXAVwn1mAZmq3tsrIEg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
