---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-config-v1
  namespace: default
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
