apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:55VH6D6tvxRsi1H+4g==,iv:794H9vdI4+uf3OcB9S87t8JecAdvKv5b+jok5eK8EEs=,tag:Efj5aBfPEnIaK2Q1U9DTeQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:8l1m1TwI3Cu71IRb9pgwiSxZYgrrX9RPMw==,iv:/bA/wP+e3FzOUO5uAbk0mUecBCOha1wk8L/+eKupPoE=,tag:W+DmWBDHfS7t0cPmLQ2VmQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:IedAeQxiGq45Z/7a9ReiwtGoAnk8Ye4sBy9vNzWYKxW4CGWs,iv:egMX1zx8odq0GrbeRfPB4/sCJKMQxHNSXMphAzrJV+0=,tag:AKu6Vj6tWnmHOntLQA4D2g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cg76rnnuuqr3ykr9hsdws3sd2frr40za7g5fje25ctwl7nh2k3lqw6rtef
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDeU5DTzZ5d3FjdEJsdW8r
            OUJFeUNudG9RaWR4b0NhZjdUUFovUktLTDAwCmYxWm9oVDBlUUhnd3RYTlpmaHly
            R1dyamI2dXF6OVQ3YlgybXNucjdjU0kKLS0tIE9nTGFyZ29wbVBMTWxDa2hldFZE
            NkZLZEszL282Q1Q3TGc2UGk2QmQ2Z1kK2tAuR7AF5Mf+yb+1EUO65+ptlKJOMoBH
            TVTNDhlPp3WsszIqh2qJnftbPf0m3vFnMP0ardQRzl15uQk734dLHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-28T03:01:15Z"
    mac: ENC[AES256_GCM,data:I7i6UWqm8YJF+2uJ/reToVmObMPpxJL0FxAAmKvTaJVpBnH1xxM/EoVlHAzY4i0tDtu3BNySza20TGO3H+Wo1NblgGhHKEN8jyrkAQRB59Sm3pX8ppyVfNWaD+UwjMeOXeL3I8HlxeozJVf81HUe+ulIFYbqng6dh/Er3HEkAOo=,iv:7DEJG8qOOXoSUl8UJfuGxf++eP7L0JFLzyhqd3w4RU4=,tag:v4XW7lecsrhTEBpeQdIEkQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
