apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:ZebDGutHddHdke4ex48bJR4cV8KVlX5L8g==,iv:pivw8/p66V6TNahrt3i8lWK650Lhtra/9yHNgKhuQgU=,tag:yv6PyXWNW3AUjrG4nA3b7Q==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:bDmAAKZRdKOIhx7N29BLxc09nSjf3S0AV665+gcbM/QxFnET,iv:jRo/lyADLLWcecNspKopmI/HjJsCmvhRvWlvBac5XnI=,tag:6LCexPkpswtG8fDtAv2Yxg==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:6pcwAjvgrZKLIoO0SA==,iv:4CBggNtMsELhx8K5uOBF4nybwZlYwRDAiMsgxzJSWOs=,tag:yXWMP/VvGculwG6+WwY7Xw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15kdjgz2v33vet626wnu8dlnhletdpeeqvgvh5t9rtwjn84jpvepszq6st3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSaXJWb1NtTjliY0Z5cG9k
            bkhQanVYZy9wZGlYM0UvOWJHb0ttRXU3d3hBCkF2L0ROSThuUmRMaXYvMjNoVzdK
            TXI1S1RtWTVBbm1CSENTYng3alZTMTQKLS0tIEMwV1RpTmw0TURNbWd2NjhuUzNs
            NlM5YkVTVU1ZSW11ZXl5blBZc2FCWG8K7rtderc1mtK97/QHHcN0F69/nWjHeMuS
            i1nvjrnGmczdgXxiDfnKgXiYJ8XgCTh+Vazfr4EkNABduEMiZDAYsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-04T03:07:28Z"
    mac: ENC[AES256_GCM,data:YYt4ZQD5RSqj/rCt5eBT+z5LZay4RN56bu84petDRhlQOYDu6UoiGxyiNzkq+SM7Dzkk/MRmI2BeazEabrAk1XohA10z76NLD8Vy3RvLjzH1H6q69FJddcEiHEHXt4zy/snNFmv010lixiybsu/QzLJbieQqvv/446LbZxUiT4I=,iv:Z0LQA6CJxxY7ciOuTC4I9BXaaeJHpdnmWNiQ6nGt8Gs=,tag:eTnwDYYde8n2qzw8SbcdTA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
