---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: coder-postgres-v15-cluster-1-noon
  namespace: database
spec:
  schedule: "0 0 13 * * *"
  immediate: true
  backupOwnerReference: self
  cluster:
    name: coder-postgres-v15-cluster-1
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: coder-postgres-v15-cluster-1-nightly
  namespace: database
spec:
  schedule: "0 0 3 * * *"
  immediate: true
  backupOwnerReference: self
  cluster:
    name: coder-postgres-v15-cluster-1
