---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-monitoring-grafana
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-database-postgres-cluster
    - name: cluster-kube-system-external-secrets
  path: ./kubernetes/apps/monitoring/grafana/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
