---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: toolhive-operator-crds
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.51.3
    digest: sha256:43f0e16b8a5a35a6e1c6e1b6a9b6849ddaad849d40d02d175b46fc9a09cea984
  url: oci://ghcr.io/stacklok/toolhive/toolhive-operator-crds
