---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: toolhive-operator-crds
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.50.0
    digest: sha256:4a581d1386cb20fbec40638cc62666a11120b802bae28aa30102fad3fc8b1996
  url: oci://ghcr.io/stacklok/toolhive/toolhive-operator-crds
