---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: toolhive-operator-crds
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.42.1
    digest: sha256:81e4152c78a29f8887a70f254d1e9b46d0261828f67b88f309dcd2307655f266
  url: oci://ghcr.io/stacklok/toolhive/toolhive-operator-crds
