---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-v15
  namespace: database
  annotations:
    kyverno.io/ignore: "true"
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:15.2
  primaryUpdateStrategy: unsupervised
  storage:
    size: 20Gi
    storageClass: longhorn
  superuserSecret:
    name: cloudnative-pg-secret
  bootstrap:
#    initdb:
#      database: homeassistant
#      owner: hass
    recovery:
      source: clusterBackup
  externalClusters:
    - name: clusterBackup
      barmanObjectStore:
        destinationPath: "https://s3.${SECRET_DOMAIN}/postgresql/postgres-v15/"
        s3Credentials:
          # Minio
          accessKeyId:
            name: cloudnative-pg-secret
            key: aws-access-key-id
          secretAccessKey:
            name: cloudnative-pg-secret
            key: aws-secret-access-key
        wal:
          maxParallel: 8
  postgresql:
    parameters:
      max_connections: "300"
      shared_buffers: 512MB
#    pg_hba: []
  monitoring:
    enablePodMonitor: true
  resources:
    requests:
      memory: "512Mi"
      cpu: "1"
    limits:
      memory: "4Gi"
  backup:
    retentionPolicy: 30d
    barmanObjectStore:
      wal:
        compression: bzip2
        maxParallel: 8
      destinationPath: "s3://postgresql/"
      endpointURL: "https://s3.${SECRET_DOMAIN}"
      serverName: postgres-v15
      s3Credentials:
        # Minio
        accessKeyId:
          name: cloudnative-pg-secret
          key: aws-access-key-id
        secretAccessKey:
          name: cloudnative-pg-secret
          key: aws-secret-access-key
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: NotIn
                values:
                  - "true"
