---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: postgres-cluster-noon
  namespace: database
spec:
  schedule: "0 0 13 * * *"
  immediate: true
  backupOwnerReference: self
  cluster:
    name: postgres-v15
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: postgres-cluster-nightly
  namespace: database
spec:
  schedule: "0 0 3 * * *"
  immediate: true
  backupOwnerReference: self
  cluster:
    name: postgres-v15
