apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:FPzDhsCxnp3WF08kNWEVIWyoTtx4LOe0X4fmsjVcT8vgBSVX,iv:8r9WzHYHfJ0lPEEymGBLh+So9rOw233ktDa5uiwffkM=,tag:+ShlF7WimvfTGoMCJ8xHRQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:5N5Q5fUIX1HQYM0qP/qjrD7ctR06n80etgcsrUb7ZjY/ZK/dyiiM3lZE+vOTAaHt+NKrR387SwO02fpE0ThVRjdkJaanY15/bU6vGGGEQfmxr5CGZ+nq4+Ddw3ot2iBIUGCeBA7p3C+tl7qP7+55i2WSuVpZ+UF7aaxh/R70Tp24pQV84aVyPpAksERctYSIdwAyRWtmZntoGnp7gJBRajyL3O2JC+He5xZDNnkKeQ==,iv:0FDF/CKH7lH6+9A4NDhtecGEBGNYajCdS3ZbJ6H2oMk=,tag:AK+gggEXEOSL9dOxnPaFdA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cg76rnnuuqr3ykr9hsdws3sd2frr40za7g5fje25ctwl7nh2k3lqw6rtef
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYS2RzdE54Q1dKNkNnYVdG
            cTF3MUVTYk5jNTQ4Sjhqa0ozVm5YL1RFWXdVClhZZVlnbHE0VG1XVG45MnlWOWVK
            ZlJHYW55N09RVDNPVFIxNy84RzkxVjgKLS0tIFFKbkpTaTdrZEFWUmVRR2dqUklW
            UFRKdmk1ZUorQll6NDBBWFQxa2o4T1kK21UWE4RdANe4zMvZ+yhzDh16dqFfwdON
            SYm0RiP8gtQ8dxKkEkhbSvUYFIG7Umzykmemxi6tsEhgq5olz64Oyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-28T03:01:15Z"
    mac: ENC[AES256_GCM,data:+hMDsmZGMr/NdcQJsf7wm3XF/U2GGb97hn/l6FgAqfa1a+LsqPaBixe4AbMvKBmergCxsKwE0aNNSnqqFRqrurWHmZ6tPGkAja74nynnRGEWWBt77+c1uhEI65pwX8/P6c/y6AVUjfBtt/IU96pnD6TJmDiCfMWsWSpnwa+4xrk=,iv:lTFfwYzrtGVRfgII6qLMXmGl3BIh/NdJX9LshH5hpcs=,tag:pzFDVGFS616p8y7/+Sh4Ew==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
