apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:mATC62bRmowrbL7YimEkqHMbvP73BB1NJRcYhgU6QyOtn9Oy,iv:xQPFUQZ5Plcbcm2wb2a7I0frMLRKTDhny2n+/nZvI5s=,tag:SQQ4nngeCvQl1UaXVOTiZA==,type:str]
    credentials.json: ENC[AES256_GCM,data:FEumnscKrUNUHqzq30nsqktUyM9rRm+Tl2e2bEaVfuWVmDrczhEih+XwOna8b8c/UJSnnWDts/727yTFpxvS22Med02gb4KfrK+gvZi4j28BnCVfkzEMw2JTiiYvausXQSKa/+TsL5cNBLQSfukLaysck9B3Jx2TIyy+EeINSF7S+/Pi1qBYTGx0DSBnFWqC11e6d9kjNRxCL+h5TrLQImX17DYScK5cyd0efHJEWQ==,iv:BD9xPFWyC7vvCLHMv4MWvQXJk5Onsm1D7Csl20bAclA=,tag:uSPudMtFeCiQvzR4LHzmhQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cg76rnnuuqr3ykr9hsdws3sd2frr40za7g5fje25ctwl7nh2k3lqw6rtef
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAybkl6K2hHZTRXbUxGQThX
            T3hwRDZVUUhZdWpBK2d0YTB1eWRYcDFHdDF3CnpzUTdNRnU0cVhLaGVIZDBQNXJE
            dlJiTXcwU281eFkxSHB2QytVNVBMajgKLS0tIHd1M0lraGJVN3Q1ZkJxVEhQcTcy
            VzlqYTFhWFJUMWJwWFg2YW9Sc1NLaHMK5b/ZoPasPH6WAaiWsxmqcUSxkwI3BKV9
            NTD0iPPj2VJ54+zoVS0vFPzAGNLNSPx4oefNAFiloJQ9Yl1O0UWh2Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-15T23:55:11Z"
    mac: ENC[AES256_GCM,data:QrDJuP8VjDt8vh/ELakAmn66BeH+CPyrr/u1Gd2H8KsNY+OpotbLC+8HrwEYvJt6Wq7gWP+d7HhtuG7v//zo9IKckoWsfXeybjUweTi6pghxoMhk0KXEEcIIHURRUpz9z51qsvwUxuxGAIPJmOZ9ALtOc5kPlrMtBksn8n3y/y8=,iv:3MinDBAd6sKvC8ynUYLy3OoOeWWJoJGkVpT0RCXHHfk=,tag:tTkVPoy8wBSFw1SMsmTJ/g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
