---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: multus
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.3.2
    digest: sha256:5e0d0f61809b9df840f2d62f7baef460dc726e4590f197ef95aae736ee056f9f
  url: oci://ghcr.io/bjw-s-labs/helm/multus
