apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:Gio8hWoydLHtYY1ai7/AxHRcJJDuTqpkNYzeC1WLUAgmCwbiu/lHoQ==,iv:WOetBqWz/08eNUBlKI75ZHhibr1hNQkIpKwfPfDG7HY=,tag:U9bCLYK7ddHWS7oNFSvvxw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15kdjgz2v33vet626wnu8dlnhletdpeeqvgvh5t9rtwjn84jpvepszq6st3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxV3JhOW9NZ3Z2amVVc0dG
            bzc5SXBncXk3K2lBTGtpSFlUWFQ4ZU9LYW5JCkVhTVVHU2Y4eFNOdWw1U2svRkZC
            dEVWUnNBeVE1azVQU0lBVUVOWGFYUVEKLS0tIFdoR1BGWHZSeVJlekhRQ05MRHRt
            dVRJSHBYZHZKZTR5RGUvUEtOODBOZjQKDf9F4qk55ecM/bosCkySLJLpVR6lphV0
            0E82muNk/XHaHXKPjRyjUcT2K+0uFWDo0Qo3Ju7AYHdpdbQy0nCo3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-04T03:07:29Z"
    mac: ENC[AES256_GCM,data:7bN8zWWb66p+lgwncMAUgfshAE/TaUXT8Yb5Su4CmUwMWiaNyvyKA5WAqLmSLJd0mwo00cnpcfbUXgJoau4G9IUtbU2g1XvYP3RiwuKPTNWeqQDE9zXyFCZR7ebYtpWaNySjE2wQ7bSrCDoFsPU6hpMCKm+YtVQi3YZyib9K8+o=,iv:EAusU0evdYxPwW8Dm0AhUM/iaTWjqrpS9mhgzmrtwO8=,tag:gnXoWp9dcWY9LRKh6W8BzA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
