---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nas-media
  namespace: media
spec:
  storageClassName: nfs-client
  resources:
    requests:
      storage: 50Gi
  volumeMode: Filesystem
  volumeName: nas-media
  accessModes:
    - ReadWriteMany
