---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mcp-platform
resources:
  - ./externalsecret.yaml
  - ./ingress.yaml
  - ./mcpremoteproxy.yaml
  - ./mcptelemetryconfig.yaml
  - ./servicemonitor.yaml
