---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
#  - ./csi-driver-nfs/ks.yaml
  - ./longhorn-system/ks.yaml
#  - ./minio/ks.yaml
  - ./nfs-subdir-external-provisioner/ks.yaml
